# Generated by Django 2.2.4 on 2019-08-29 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clima', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clima',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
